# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  sync:
    name: Sync main branch from NVIDIA/TensorRT-LLM
    runs-on: ubuntu-latest
    if: github.repository != 'NVIDIA/TensorRT-LLM'
    permissions:
      contents: write
    steps:
      - name: Sync fork
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: NVIDIA/TensorRT-LLM
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
